

RAINBOW_CROSSFADE = 0x25
RED_GRADUALLY = 0x26
GREEN_GRADUALLY = 0x27
BLUE_GRADUALLY = 0x28
YELLOW_GRADUALLY = 0x29
BLUE_GREEN_GRADUALLY = 0x2a
PURPLE_GRADUALLY = 0x2b
WHITE_GRADUALLY = 0x2c
RED_GREEN_CROSSFADE = 0x2d
RED_BLUE_CROSSFADE = 0x2e
GREEN_BLUE_CROSSFADE = 0x2f
RAINBOW_STROBE = 0x30
RED_STROBE = 0x31
GREEN_STROBE = 0x32
BLUE_STROBE = 0x33
YELLOW_STROBE = 0x34
BLUE_GREEN_STROBE = 0x35
PURPLE_STROBE = 0x36
WHITE_STROBE = 0x37
RAINBOW_FLASH = 0x38
NORMAL = 0x61


_VALUE_TO_NAME = {
    RAINBOW_CROSSFADE: 'RAINBOW_CROSSFADE',
    RED_GRADUALLY: 'RED_GRADUALLY',
    GREEN_GRADUALLY: 'GREEN_GRADUALLY',
    BLUE_GRADUALLY: 'BLUE_GRADUALLY',
    YELLOW_GRADUALLY: 'YELLOW_GRADUALLY',
    BLUE_GREEN_GRADUALLY: 'BLUE_GREEN_GRADUALLY',
    PURPLE_GRADUALLY: 'PURPLE_GRADUALLY',
    WHITE_GRADUALLY: 'WHITE_GRADUALLY',
    RED_GREEN_CROSSFADE: 'RED_GREEN_CROSSFADE',
    RED_BLUE_CROSSFADE: 'RED_BLUE_CROSSFADE',
    GREEN_BLUE_CROSSFADE: 'GREEN_BLUE_CROSSFADE',
    RAINBOW_STROBE: 'RAINBOW_STROBE',
    GREEN_STROBE: 'GREEN_STROBE',
    BLUE_STROBE: 'BLUE_STROBE',
    YELLOW_STROBE: 'YELLOW_STROBE',
    BLUE_GREEN_STROBE: 'BLUE_GREEN_STROBE',
    PURPLE_STROBE: 'PURPLE_STROBE',
    WHITE_STROBE: 'WHITE_STROBE',
    RAINBOW_FLASH: 'RAINBOW_FLASH',
    NORMAL: 'NORMAL',
}


def _data_change_mode(mode, slowness):  # slowness is a integer value 1 to 49
    d = [0x61, mode, slowness, 0x0f]
    return d
